import { Github, Globe, Mail, ExternalLink, Bot, BrainCircuit, Server, Database, Code, FileCode, Blocks, Infinity, Flame, FileJson, Laptop, Phone, Tablet, MonitorSmartphone, Rocket, Webhook, Cpu, CircuitBoard, TestTube, AppWindow, GraduationCap, Briefcase, Calendar, Globe as Website } from "lucide-react";
import {
  SiSwift,
  SiApple,
  SiBun,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiVercel,
  SiAngular,
  SiSelenium,
  SiOpenjdk,
  SiScala,
  SiMacos,
  SiAppstore,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiRedis,
  SiPostgresql,
  SiHono,
  SiMysql,
  SiMongodb,
  SiSqlite,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiFlask,
  SiDocker,
  SiKubernetes,
  SiAmazon,
  SiGooglecloud,
  SiFirebase,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiSpringboot,
  SiYoutube,
} from "react-icons/si";
import { FaTwitter, FaInstagram, FaLinkedin } from "react-icons/fa";

export const techIconMap = {
  Swift: SiSwift,
  SwiftUI: SiSwift,
  iOS: SiApple,
  iPadOS: SiApple,
  macOS: SiMacos,
  Bun: SiBun,
  Python: SiPython,
  React: SiReact,
  NextJS: SiNextdotjs,
  Vercel: SiVercel,
  Angular: SiAngular,
  Selenium: SiSelenium,
  Java: SiOpenjdk,
  Spring: SiSpringboot,
  Scala: SiScala,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML: SiHtml5,
  CSS: SiCss3,
  TailwindCSS: SiTailwindcss,
  Git: SiGit,
  Redis: SiRedis,
  SQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  SQLite: SiSqlite,
  PostgreSQL: SiPostgresql,
  Database: Database,
  Node: SiNodedotjs,
  Express: SiExpress,
  Django: SiDjango,
  Flask: SiFlask,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  AWS: SiAmazon,
  GCP: SiGooglecloud,
  Firebase: SiFirebase,
  Hono: SiHono,
  "Machine Learning": BrainCircuit,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  "Scikit Learn": SiScikitlearn,
  LlamaStack: Bot,
  Code: Code,
  API: Webhook,
  "Full Stack": MonitorSmartphone,
  Mobile: Phone,
  Data: Database,
} as const;

export const socialIconMap = {
  GitHub: Github,
  Website: Website,
  Email: Mail,
  AppStore: SiAppstore,
  TestFlight: SiApple,
  Apple: SiApple,
  Twitter: FaTwitter,
  Instagram: FaInstagram,
  LinkedIn: FaLinkedin,
  External: ExternalLink,
  YouTube: SiYoutube,
  Code: Code,
  Education: GraduationCap,
  Work: Briefcase,
  Calendar: Calendar,
} as const;

// Add type definitions to help catch undefined icons at compile time
export type TechIconType = keyof typeof techIconMap;
export type SocialIconType = keyof typeof socialIconMap; 