import type { LucideIcon } from 'lucide-react';
import {
  // Only keep the icons that are actually used in your components
  // Remove or comment out unused icons
  // Globe,
  // Server,
  // FileCode,
  // Blocks,
  // Infinity,
  // Flame,
  // FileJson,
  // Laptop,
  // Tablet,
  // Rocket,
  // Cpu,
  // CircuitBoard,
  // TestTube,
  // AppWindow,
  // Add any icons that are actually used in your components
  Github,
  Globe as Website,
  Mail,
  ExternalLink,
  Bot,
  BrainCircuit,
  Database,
  Code,
  MonitorSmartphone,
  Phone,
  GraduationCap,
  Briefcase,
  Calendar,
  Webhook,
} from 'lucide-react';
import { FaTwitter, FaInstagram, FaLinkedin } from 'react-icons/fa';
import {
  SiSwift,
  SiApple,
  SiBun,
  SiPython,
  SiReact,
  SiNextdotjs,
  SiVercel,
  SiAngular,
  SiSelenium,
  SiOpenjdk,
  SiScala,
  SiMacos,
  SiAppstore,
  SiTypescript,
  SiJavascript,
  SiHtml5,
  SiCss3,
  SiGit,
  SiRedis,
  SiPostgresql,
  SiHono,
  SiMysql,
  SiMongodb,
  SiSqlite,
  SiTailwindcss,
  SiNodedotjs,
  SiExpress,
  SiDjango,
  SiFlask,
  SiDocker,
  SiKubernetes,
  SiAmazon,
  SiGooglecloud,
  SiFirebase,
  SiTensorflow,
  SiPytorch,
  SiScikitlearn,
  SiSpringboot,
  SiYoutube,
} from 'react-icons/si';

export type Icon = LucideIcon;

export const techIconMap = {
  database: Database,
  ai: BrainCircuit,
  bot: Bot,
  code: Code,
  mobile: MonitorSmartphone,
  phone: Phone,
  database_alt: Database,
  api: Webhook,
  Swift: SiSwift,
  SwiftUI: SiSwift,
  iOS: SiApple,
  iPadOS: SiApple,
  macOS: SiMacos,
  Bun: SiBun,
  Python: SiPython,
  React: SiReact,
  NextJS: SiNextdotjs,
  Vercel: SiVercel,
  Angular: SiAngular,
  Selenium: SiSelenium,
  Java: SiOpenjdk,
  Spring: SiSpringboot,
  Scala: SiScala,
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  HTML: SiHtml5,
  CSS: SiCss3,
  TailwindCSS: SiTailwindcss,
  Git: SiGit,
  Redis: SiRedis,
  SQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  SQLite: SiSqlite,
  PostgreSQL: SiPostgresql,
  Node: SiNodedotjs,
  Express: SiExpress,
  Django: SiDjango,
  Flask: SiFlask,
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  AWS: SiAmazon,
  GCP: SiGooglecloud,
  Firebase: SiFirebase,
  Hono: SiHono,
  'Machine Learning': BrainCircuit,
  TensorFlow: SiTensorflow,
  PyTorch: SiPytorch,
  'Scikit Learn': SiScikitlearn,
  LlamaStack: Bot,
  API: Webhook,
  'Full Stack': MonitorSmartphone,
  Data: Database,
} as const;

export const socialIconMap = {
  github: Github,
  website: Website,
  email: Mail,
  AppStore: SiAppstore,
  TestFlight: SiApple,
  Apple: SiApple,
  Twitter: FaTwitter,
  Instagram: FaInstagram,
  LinkedIn: FaLinkedin,
  External: ExternalLink,
  YouTube: SiYoutube,
  code: Code,
  education: GraduationCap,
  work: Briefcase,
  calendar: Calendar,
} as const;

// Add type definitions to help catch undefined icons at compile time
export type TechIconType = keyof typeof techIconMap;
export type SocialIconType = keyof typeof socialIconMap;

export const Icons = {
  // Only keep the icons that are actually used
  // Remove unused icon exports
  link: ExternalLink,
  code: Code,
  education: GraduationCap,
  work: Briefcase,
  calendar: Calendar,
} as const;
